<a href="https://colab.research.google.com/github/Tejas325-creator/Tejas325-creator/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###NUMPY :

python library , used for working with arrays .

In [1]:
import numpy

BASIC OPERATIONS :

In [3]:
import numpy as np
#np --> allies

Creating array

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
type(a)
# nd --> n dimensional array

numpy.ndarray

In [7]:
a = np.array([1,2,3], dtype = float)
print(a)

[1. 2. 3.]


In [8]:
a = np.array([1,2,3], dtype = str)
print(a)

['1' '2' '3']


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
len(a)

3

In [12]:
len(b)

2

In [13]:
# Get dimeension of a numpy array :
a.ndim

1

In [14]:
b.ndim

2

### WHY USE NUMPY ???




In [16]:
# Get a shape of a numpy array :
a.shape

(3,)

In [17]:
b.shape

(2, 3)

In [18]:
a.dtype

dtype('<U1')

### ACCESING/CHANGING A SPECIFIC ELEMENTS , ROWS AND COLUMNS ETC.

In [20]:
a = np.array([[1,2,3,4,5,6,7] , [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a.ndim

2

In [22]:
#Got a specific elements [r,c]:
a[0,3]
# 0 is the first index  that is our 1st element nd in that element the 3rd element counting from the index 0  : 3rd one is "4"

np.int64(4)

In [23]:
a[1,0]

np.int64(8)

In [25]:
# Get a specific row from a numpy array
a[0,:]
# You have to print whole row so use ":"

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
# GET a specific column from a numpy array
a[:,0]

array([1, 8])

In [27]:
a[:,2]

array([ 3, 10])

In [28]:
a[0,3] = 40
print(a)
# We can change the array so numpy is mutable : here we change the elements in arrays

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
# Change the 5th column in 1st row to 50
a[0,4] = 50
print(a)

[[ 1  2  3 40 50  6  7]
 [ 8  9 10 11 12 13 14]]


### ZERO/ONES METHOD IN NUMPY :

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((3,3) , dtype = 'int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [37]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
#full : We have to create a entity of the same number and want to give that number :
np.full((3,3),50, dtype = 'float32')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]], dtype=float32)

In [39]:
vara = 20
np.full((3,3),vara, dtype = 'float32')

array([[20., 20., 20.],
       [20., 20., 20.],
       [20., 20., 20.]], dtype=float32)

In [40]:
np.random.rand(4,4)
# Gives random matrix

array([[0.10002709, 0.20130256, 0.85985049, 0.80301848],
       [0.90462884, 0.87408986, 0.28244705, 0.59655226],
       [0.18795988, 0.1856416 , 0.86456041, 0.77429215],
       [0.7943999 , 0.39477878, 0.44021362, 0.02412669]])

In [41]:
np.random.randint(-4,1,size = (3,3))
# If we want random integer array

array([[-2, -3,  0],
       [-1,  0, -2],
       [-1, -2, -1]])

In [42]:
# I want a random integer between 1 to 5
np.random.randint(1,5,size = (3,3))

array([[2, 4, 4],
       [1, 1, 2],
       [1, 4, 1]])

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# IDNETITY MATRIX IS :
# [ 1 0
 # 0 1 ]

### PRACTISE QUESTIONS :

EXTRACT all the first 3 rows of the last 5 columns in a given numpy 2D array 'a' ?

In [48]:
a = np.array ([[3,4,5,6,0,0],
[20,30,40,50,60,0],
[12,12,12,12,12,0],
[11,21,31,41,51,61],
               [12,13,15,1,33,3]])
# Given array

In [49]:
a

array([[ 3,  4,  5,  6,  0,  0],
       [20, 30, 40, 50, 60,  0],
       [12, 12, 12, 12, 12,  0],
       [11, 21, 31, 41, 51, 61],
       [12, 13, 15,  1, 33,  3]])

In [ ]:
#OUTPUT SHOULD BE :
4,5,6,0,0
30, 40, 50, 60,  0
12, 12, 12, 12,  0





In [50]:
a [0:3 , -5 :]
# So after comma is columns so we use -5 that is from backside as we need last 5 columns
# and for first 3 rows we use 0 : 3

array([[ 4,  5,  6,  0,  0],
       [30, 40, 50, 60,  0],
       [12, 12, 12, 12,  0]])

In [51]:
# For printing first 3 rows :
a[0,3]

np.int64(6)

Q.GIVEN A +VE NUMBER 'n' greater than 2 , create a numpy array of size(nxn) with all zeroes and one such that the ones make a shape of "+"

In [ ]:
LIKE :
INPUT 1 :
3
OUTPUT 1 :
[0 1 0 ]
[1 1 1 ]
[0 1 0 ]

In [52]:
import numpy as np

def plus_pattern(n):
    if n <= 2:
        raise ValueError("n must be greater than 2")

    arr = np.zeros((n, n), dtype=int)
    mid = n // 2

    arr[mid, :] = 1      # horizontal line
    arr[:, mid] = 1      # vertical line

    return arr

# Example
n = 5
print(plus_pattern(n))


[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
